//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbankinh.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> product { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createonutc { get; set; }
    }
}
