//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbankinh.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string avatar { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string shortdes { get; set; }
        public string fulldescription { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> pricediscount { get; set; }
        public Nullable<int> typeld { get; set; }
        public string slug { get; set; }
        public Nullable<int> brandid { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> showonhomepage { get; set; }
        public Nullable<int> displayoder { get; set; }
        public Nullable<System.DateTime> createonutc { get; set; }
        public Nullable<System.DateTime> updateonutc { get; set; }
        [NotMapped]
       public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
