//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbankinh.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string ho { get; set; }
        public string ten { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> isadmin { get; set; }
    }
}
